# Angle Mechanisms

In this notebook, we will lay out our approach for a Neural Network approach to predict a pose based on landmark. Additionally, we are storing out angle calculation and perspectively our angle error calculation.

## Getting the Data

### Image upload and Preprocessing, single picture

In [1]:
import tensorflow as tf
import tensorflow_hub as hub
from tensorflow_docs.vis import embed
import numpy as np
import cv2
import os
import pandas as pd

# Import matplotlib libraries
from matplotlib import pyplot as plt
from matplotlib.collections import LineCollection
import matplotlib.patches as patches

# Some modules to display an animation using imageio.
import imageio
from IPython.display import HTML, display


In [2]:
# Model Initialization
model_name = "movenet_lightning"
module = hub.load("https://tfhub.dev/google/movenet/singlepose/lightning/4")
input_size = 192
model = module.signatures['serving_default']


In [60]:
# Choose image file and preprocess

image_path = "../mika_poses/87f61309-0e27-4508-affa-11b83f4f1b67.jpg"
image = tf.io.read_file(image_path)
image = tf.image.decode_jpeg(image)

# Resize and pad the image to keep the aspect ratio and fit the expected size.
input_image = tf.expand_dims(image, axis=0)
input_image = tf.image.resize_with_pad(input_image, input_size, input_size)


In [61]:
image


<tf.Tensor: shape=(656, 829, 3), dtype=uint8, numpy=
array([[[129,  64,  32],
        [124,  59,  27],
        [127,  62,  30],
        ...,
        [197, 199, 198],
        [194, 196, 195],
        [  2,   4,   3]],

       [[131,  66,  34],
        [126,  61,  29],
        [126,  61,  29],
        ...,
        [197, 199, 198],
        [194, 196, 195],
        [  1,   3,   2]],

       [[135,  70,  38],
        [129,  64,  32],
        [126,  61,  29],
        ...,
        [196, 198, 197],
        [194, 196, 195],
        [  1,   3,   2]],

       ...,

       [[143, 146,  41],
        [147, 150,  45],
        [147, 150,  45],
        ...,
        [169, 170, 164],
        [166, 167, 161],
        [  2,   2,   0]],

       [[144, 147,  40],
        [148, 151,  44],
        [148, 151,  46],
        ...,
        [170, 171, 165],
        [166, 167, 161],
        [  2,   2,   0]],

       [[146, 150,  40],
        [149, 153,  43],
        [148, 151,  46],
        ...,
        [170, 171, 16

In [55]:
# Detect landmarks on image
model = module.signatures["serving_default"]
input_image = tf.cast(input_image, dtype=tf.int32)
input_image = input_image[..., :3]
outputs = model(input_image)

# 1D array of xyz coordinates. X1, Y1, Z1, X2, ... , Yn, Zn format
xyz_individual = outputs["output_0"].numpy()


In [6]:
xyz_individual


array([[[[0.38618642, 0.5001651 , 0.61137486],
         [0.37802157, 0.51019275, 0.6280255 ],
         [0.3773265 , 0.48961085, 0.5317528 ],
         [0.3910056 , 0.52356184, 0.6837949 ],
         [0.39103925, 0.4748915 , 0.823982  ],
         [0.4432593 , 0.54984444, 0.7773363 ],
         [0.44181532, 0.44503877, 0.8072547 ],
         [0.4291618 , 0.62940717, 0.763232  ],
         [0.4343538 , 0.3645373 , 0.7827731 ],
         [0.3685537 , 0.65625304, 0.56193423],
         [0.3765012 , 0.35011956, 0.42450994],
         [0.6197113 , 0.52747464, 0.72385025],
         [0.6196584 , 0.4666146 , 0.79227793],
         [0.6398416 , 0.65718675, 0.68750316],
         [0.6426125 , 0.328991  , 0.7633832 ],
         [0.76167035, 0.66402024, 0.8026122 ],
         [0.7670605 , 0.31065577, 0.8474749 ]]]], dtype=float32)

### Drawing the Landmarks

In [56]:
# Helper method for drawing landmarks
def draw_prediction_on_image(
    image, keypoints_with_scores, crop_region=None, close_figure=False,
    output_image_height=None):
  """Draws the keypoint predictions on image.

  Args:
    image: A numpy array with shape [height, width, channel] representing the
      pixel values of the input image.
    keypoints_with_scores: A numpy array with shape [1, 1, 17, 3] representing
      the keypoint coordinates and scores returned from the MoveNet model.
    crop_region: A dictionary that defines the coordinates of the bounding box
      of the crop region in normalized coordinates (see the init_crop_region
      function below for more detail). If provided, this function will also
      draw the bounding box on the image.
    output_image_height: An integer indicating the height of the output image.
      Note that the image aspect ratio will be the same as the input image.

  Returns:
    A numpy array with shape [out_height, out_width, channel] representing the
    image overlaid with keypoint predictions.
  """
  height, width, channel = image.shape
  aspect_ratio = float(width) / height
  fig, ax = plt.subplots(figsize=(12 * aspect_ratio, 12))
  # To remove the huge white borders
  fig.tight_layout(pad=0)
  ax.margins(0)
  ax.set_yticklabels([])
  ax.set_xticklabels([])
  plt.axis('off')

  im = ax.imshow(image)
  line_segments = LineCollection([], linewidths=(4), linestyle='solid')
  ax.add_collection(line_segments)
  # Turn off tick labels
  scat = ax.scatter([], [], s=60, color='#FF1493', zorder=3)

  (keypoint_locs, keypoint_edges,
   edge_colors) = _keypoints_and_edges_for_display(
       keypoints_with_scores, height, width)

  line_segments.set_segments(keypoint_edges)
  line_segments.set_color(edge_colors)
  if keypoint_edges.shape[0]:
    line_segments.set_segments(keypoint_edges)
    line_segments.set_color(edge_colors)
  if keypoint_locs.shape[0]:
    scat.set_offsets(keypoint_locs)

  if crop_region is not None:
    xmin = max(crop_region['x_min'] * width, 0.0)
    ymin = max(crop_region['y_min'] * height, 0.0)
    rec_width = min(crop_region['x_max'], 0.99) * width - xmin
    rec_height = min(crop_region['y_max'], 0.99) * height - ymin
    rect = patches.Rectangle(
        (xmin,ymin),rec_width,rec_height,
        linewidth=1,edgecolor='b',facecolor='none')
    ax.add_patch(rect)

  fig.canvas.draw()
  image_from_plot = np.frombuffer(fig.canvas.tostring_rgb(), dtype=np.uint8)
  image_from_plot = image_from_plot.reshape(
      fig.canvas.get_width_height()[::-1] + (3,))
  plt.close(fig)
  if output_image_height is not None:
    output_image_width = int(output_image_height / height * width)
    image_from_plot = cv2.resize(
        image_from_plot, dsize=(output_image_width, output_image_height),
         interpolation=cv2.INTER_CUBIC)
  return image_from_plot


In [58]:
draw_prediction_on_image(image, keypoints_with_scores)


NameError: name 'image_from_plot' is not defined

### Uploading whole image folder 

In [9]:
# Get list of image file names in given directory
dir_path_train_dd = "../clean"
file_names = []
for entry in os.listdir(dir_path_train_dd):
    file_names.append(entry)


In [10]:
# Create DF of xyz values
df = []
image_names = []

for file in file_names:
    image_names.append(dir_path_train_dd)
    dir_path_train_dd = f"../clean/{file}"
    if not file.endswith((".jpg", ".png")):
        pass
    else:
#       print(dir_path_train_dd)
        image = tf.io.read_file(dir_path_train_dd)
        image = tf.image.decode_jpeg(image)
        input_image = tf.expand_dims(image, axis=0)
        input_image = tf.image.resize_with_pad(input_image, input_size, input_size)
        input_image = input_image[..., :3]

        model = module.signatures["serving_default"]
        input_image = tf.cast(input_image, dtype=tf.int32)
        outputs = model(input_image)
        df.append(outputs["output_0"].numpy().reshape(51).tolist())


In [11]:
data = pd.DataFrame(df)


In [12]:
data["label"] = "goddess"


In [13]:
data.head(3)


0         1         2         3         4         5         6  \
0  0.614686  0.366069  0.722571  0.612122  0.350986  0.643456  0.612995   
1  0.534696  0.722514  0.564541  0.529799  0.733964  0.405342  0.526650   
2  0.569520  0.529188  0.600391  0.572470  0.513902  0.517100  0.575602   

          7         8         9  ...        42        43        44        45  \
0  0.350938  0.715975  0.563880  ...  0.515043  0.705208  0.887617  0.685450   
1  0.732507  0.399033  0.498358  ...  0.471535  0.375810  0.738872  0.586279   
2  0.515343  0.508116  0.547930  ...  0.502984  0.773414  0.708214  0.674067   

         46        47        48        49        50    label  
0  0.883067  0.797600  0.667293  0.864593  0.652386  goddess  
1  0.311128  0.580621  0.628086  0.273356  0.892580  goddess  
2  0.870783  0.614912  0.665915  0.863403  0.627865  goddess  

[3 rows x 52 columns]

In [14]:
# Create DF of xyz values
df = []
xyz = []
for file in file_names:
    dir_path_train_dd = f"../clean/{file}"
    if not file.endswith((".jpg", ".png")):
        pass
    else:
#         print(dir_path_train_dd)
        image = tf.io.read_file(dir_path_train_dd)
        image = tf.image.decode_jpeg(image)
        input_image = tf.expand_dims(image, axis=0)
        input_image = tf.image.resize_with_pad(input_image, input_size, input_size)
        input_image = input_image[..., :3]

        model = module.signatures["serving_default"]
        input_image = tf.cast(input_image, dtype=tf.int32)
        outputs = model(input_image)
        df.append(outputs["output_0"].numpy().reshape(51).tolist())
        xyz.append(outputs["output_0"].numpy()[0][0])


## Angle Calculator

In [15]:
# Getting specific image out of xyz-coordinate file and transforming it to 2D (renamed to l for simplicity)

image_landmarks = xyz[6][:, :-1]
lm = image_landmarks
lm


array([[0.66960835, 0.35614344],
       [0.67016566, 0.33723804],
       [0.6718497 , 0.33988258],
       [0.6360858 , 0.3092922 ],
       [0.63745785, 0.31444016],
       [0.5863172 , 0.33249542],
       [0.5807426 , 0.331631  ],
       [0.70875835, 0.27349722],
       [0.69670475, 0.2676103 ],
       [0.7763366 , 0.17736372],
       [0.75954664, 0.1910256 ],
       [0.40240893, 0.53494716],
       [0.40276784, 0.5312333 ],
       [0.56703186, 0.63760805],
       [0.57365006, 0.6361872 ],
       [0.7234893 , 0.7441256 ],
       [0.7093338 , 0.7298353 ]], dtype=float32)

In [16]:
# Used Keypoints in data (corresponding to row number)

KEYPOINT_DICT = {
    'nose': 0,
    'left_eye': 1,
    'right_eye': 2,
    'left_ear': 3,
    'right_ear': 4,
    'left_shoulder': 5,
    'right_shoulder': 6,
    'left_elbow': 7,
    'right_elbow': 8,
    'left_wrist': 9,
    'right_wrist': 10,
    'left_hip': 11,
    'right_hip': 12,
    'left_knee': 13,
    'right_knee': 14,
    'left_ankle': 15,
    'right_ankle': 16
}


In [39]:
# Function for getting angles for single image input,
# returns dict with angle name as key and list with only the values

def angle_function(lm):

    landmark_dict = {
    'landmarks_left_elbow' : (lm[5], lm[7], lm[9]),
    'landmarks_right_elbow' : (lm[6], lm[8], lm[10]),
    'landmarks_left_shoulder' : (lm[7], lm[5], lm[11]),
    'landmarks_right_shoulder' : (lm[8], lm[6], lm[12]),
    'landmarks_hip_left' : (lm[5], lm[11], lm[13]),
    'landmarks_hip_right' : (lm[6], lm[12], lm[14]),
    'landmarks_left_knee' : (lm[11], lm[13], lm[15]),
    'landmarks_right_knee' : (lm[12], lm[14], lm[16])
        }
    print (landmark_dict)
    def angle_calculator(landmarks):

        # Converting the points into numpy arrays
        p1 = np.array(landmarks[0])
        p2 = np.array(landmarks[1])
        p3 = np.array(landmarks[2])
        print(p1,p2,p3)
        # Creating the Vectors between two points
        vec_p1 = p1-p2
        vec_p2 = p3-p2
        print (vec_p1,vec_p2)
        # Calculating the cosine of the angle
        cosine_angle = np.dot(vec_p1,vec_p2) / (np.linalg.norm(vec_p1)*np.linalg.norm(vec_p2))

        #clipping cosine angle
        cosine_angle = np.clip(cosine_angle, -1, 1)
        # Calculating angle
        angle = np.arccos(cosine_angle)

        # Calculating degrees
        angle_degrees = np.degrees(angle)

        return angle_degrees

    angle_name_list = ['angle_elbow_left',
                   'angle_elbow_right',
                   'angle_shoulder_left',
                   'angle_shoulder_right',
                   'angle_hip_left',
                   'angle_hip_right',
                   'angle_knee_left',
                   'angle_knee_right',
                  ]

    angle_dict = {}

    for dictkey, listkey in zip(landmark_dict, angle_name_list):
        i = angle_calculator(landmark_dict[dictkey])
        angle_dict[listkey] = i

    angle_list = [angle_dict[key] for key in angle_dict]

    return angle_dict, angle_list


In [40]:
angle_function(test_pose)


{'landmarks_left_elbow': (array([0.4432593 , 0.54984444], dtype=float32), array([0.4291618 , 0.62940717], dtype=float32), array([0.3685537 , 0.65625304], dtype=float32)), 'landmarks_right_elbow': (array([0.44181532, 0.44503877], dtype=float32), array([0.4343538, 0.3645373], dtype=float32), array([0.3765012 , 0.35011956], dtype=float32)), 'landmarks_left_shoulder': (array([0.4291618 , 0.62940717], dtype=float32), array([0.4432593 , 0.54984444], dtype=float32), array([0.6197113 , 0.52747464], dtype=float32)), 'landmarks_right_shoulder': (array([0.4343538, 0.3645373], dtype=float32), array([0.44181532, 0.44503877], dtype=float32), array([0.6196584, 0.4666146], dtype=float32)), 'landmarks_hip_left': (array([0.4432593 , 0.54984444], dtype=float32), array([0.6197113 , 0.52747464], dtype=float32), array([0.6398416 , 0.65718675], dtype=float32)), 'landmarks_hip_right': (array([0.44181532, 0.44503877], dtype=float32), array([0.6196584, 0.4666146], dtype=float32), array([0.6426125, 0.328991 ], d

({'angle_elbow_left': 123.93837576868602,
  'angle_elbow_right': 109.289404233378,
  'angle_shoulder_left': 107.27296770698257,
  'angle_shoulder_right': 102.21279096024998,
  'angle_hip_left': 91.59633667087346,
  'angle_hip_right': 92.55185242877225,
  'angle_knee_left': 102.03191198644711,
  'angle_knee_right': 107.8503759236781},
 [123.93837576868602,
  109.289404233378,
  107.27296770698257,
  102.21279096024998,
  91.59633667087346,
  92.55185242877225,
  102.03191198644711,
  107.8503759236781])

## Angle Comparison Tool

In [17]:
# This loop creates a list of lists with the angle value for each picture respectively

lst = []
for x in xyz:
    lst.append(angle_function(x[:, :-1])[1])

# Dataframe for the list
df = pd.DataFrame(lst)


NameError: name 'angle_function' is not defined

In [18]:
# Angle name list for the column names of the dataframe
angle_name_list = ['angle_elbow_left',
                   'angle_elbow_right',
                   'angle_shoulder_left',
                   'angle_shoulder_right',
                   'angle_hip_left',
                   'angle_hip_right',
                   'angle_knee_left',
                   'angle_knee_right',
                  ]

# Adding the created column names
df.columns = angle_name_list


AttributeError: 'list' object has no attribute 'columns'

In [19]:
# Getting image (path) names to name the indices
index_image_names = pd.Index(image_names)[1:]

# set index
df.set_index(index_image_names, inplace=True)


AttributeError: 'list' object has no attribute 'set_index'

In [215]:
df.head(5)


angle_elbow_left  angle_elbow_right  \
../clean/00000372.jpg        161.533622         167.843977   
../clean/00000414.jpg        156.647111         161.688982   
../clean/00000158.jpg        163.160640         168.443158   
../clean/00000164.jpg        159.131123         162.453301   
../clean/00000170.jpg        161.461897         159.272757   

                       angle_shoulder_left  angle_shoulder_right  \
../clean/00000372.jpg           176.212090            179.972024   
../clean/00000414.jpg           172.806634            170.628852   
../clean/00000158.jpg           163.976623            173.624648   
../clean/00000164.jpg           175.071327            176.938227   
../clean/00000170.jpg           178.728352            179.944047   

                       angle_hip_left  angle_hip_right  angle_knee_left  \
../clean/00000372.jpg       64.985133        65.501503       155.154463   
../clean/00000414.jpg       76.427716        76.186424       178.631264   
../clean/00000158.jpg       83.535028        79.592601       174.322075   
../clean/00000164.jpg       67.050041        66.100435       170.020585   
../clean/00000170.jpg       63.241979        62.176024       172.617380   

                       angle_knee_right  
../clean/00000372.jpg        154.631616  
../clean/00000414.jpg        177.908468  
../clean/00000158.jpg        172.935975  
../clean/00000164.jpg        173.788581  
../clean/00000170.jpg        170.075123

In [48]:
# df.to_csv('/Users/lennartjanssen/code/lennijanssen/angles_test')


## Angle Error & Score

In [52]:
#Finding values for the best pose

# Choose image file and preprocess

image_path = "../clean/00000144.jpg"
image = tf.io.read_file(image_path)
image = tf.image.decode_jpeg(image)

# Resize and pad the image to keep the aspect ratio and fit the expected size.
input_image = tf.expand_dims(image, axis=0)
input_image = tf.image.resize_with_pad(input_image, input_size, input_size)


# Detect landmarks on image
model = module.signatures["serving_default"]
input_image = tf.cast(input_image, dtype=tf.int32)
input_image = input_image[..., :3]
outputs = model(input_image)

# 1D array of xyz coordinates. X1, Y1, Z1, X2, ... , Yn, Zn format
best_pose = outputs["output_0"].numpy()[:, :, :, :-1][0][0]


In [53]:
#Finding values for the test pose

# Choose image file and preprocess

image_path = "../mika_poses/87f61309-0e27-4508-affa-11b83f4f1b67.jpg"
image = tf.io.read_file(image_path)
image = tf.image.decode_jpeg(image)

# Resize and pad the image to keep the aspect ratio and fit the expected size.
input_image = tf.expand_dims(image, axis=0)
input_image = tf.image.resize_with_pad(input_image, input_size, input_size)


# Detect landmarks on image
model = module.signatures["serving_default"]
input_image = tf.cast(input_image, dtype=tf.int32)
input_image = input_image[..., :3]
outputs = model(input_image)

# 1D array of xyz coordinates. X1, Y1, Z1, X2, ... , Yn, Zn format
test_pose = outputs["output_0"].numpy()[:, :, :, :-1][0][0]


In [46]:
test_pose


array([[0.38618642, 0.5001651 ],
       [0.37802157, 0.51019275],
       [0.3773265 , 0.48961085],
       [0.3910056 , 0.52356184],
       [0.39103925, 0.4748915 ],
       [0.4432593 , 0.54984444],
       [0.44181532, 0.44503877],
       [0.4291618 , 0.62940717],
       [0.4343538 , 0.3645373 ],
       [0.3685537 , 0.65625304],
       [0.3765012 , 0.35011956],
       [0.6197113 , 0.52747464],
       [0.6196584 , 0.4666146 ],
       [0.6398416 , 0.65718675],
       [0.6426125 , 0.328991  ],
       [0.76167035, 0.66402024],
       [0.7670605 , 0.31065577]], dtype=float32)

In [34]:
from operator import truediv

def angle_comparer(test, best):

    # get angles for each pose
    best_pose_angles = angle_function(best)[1]
    test_pose_angles = angle_function(test)[1]

    # find differences between each by substraction
    angle_substraction = [a - b for a, b in zip(best_pose_angles, test_pose_angles)]

    # change values to absolute values
    angle_difference = list(map(abs, angle_substraction))

    # find percentages for each pose
    test_angle_percentage = list(map(truediv, test_pose_angles, best_pose_angles))

    # find absolute difference by percentage
    test_angle_percentage_diff = [round(abs(x-1),2) for x in test_angle_percentage]

    # find average percentage difference
    average_percentage_diff = round(sum(test_angle_percentage_diff)/len(test_angle_percentage_diff),2)


    return test_angle_percentage_diff, average_percentage_diff


In [44]:
xyz_individual


array([[[[0.38598356, 0.49753022, 0.6072763 ],
         [0.37798187, 0.5069721 , 0.56672657],
         [0.3781268 , 0.48525882, 0.47344404],
         [0.39216703, 0.52232057, 0.5818483 ],
         [0.3929512 , 0.47008514, 0.7714728 ],
         [0.4459523 , 0.55220366, 0.66690886],
         [0.44657677, 0.44743463, 0.7753733 ],
         [0.42848107, 0.6321182 , 0.74485385],
         [0.4307708 , 0.36147892, 0.70483917],
         [0.36523855, 0.6564479 , 0.4787657 ],
         [0.3680428 , 0.34933776, 0.32970506],
         [0.62294626, 0.5297642 , 0.62674755],
         [0.62323534, 0.46477315, 0.7083429 ],
         [0.6395048 , 0.6570128 , 0.7874033 ],
         [0.6434806 , 0.33077243, 0.7329977 ],
         [0.7599611 , 0.6639534 , 0.6847806 ],
         [0.767637  , 0.31096762, 0.7782027 ]]]], dtype=float32)

In [48]:
angle_comparer(xyz_individual[0][0],xyz_individual[0][0])


([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 0.0)

In [50]:
c = [[[[0.64837456 0.5342141  0.6274136 ]
   [0.5953814  0.5793327  0.810975  ]
   [0.59395033 0.4837774  0.7779271 ]
   [0.62343025 0.63051575 0.5011229 ]
   [0.6252846  0.4196639  0.61263466]
   [0.8040175  0.79117095 0.59511864]
   [0.8403652  0.29704118 0.70782924]
   [0.9360502  0.8255879  0.01523436]
   [0.9486384  0.20740595 0.02684249]
   [0.85183907 0.6181905  0.04781246]
   [0.8531863  0.49002466 0.23143597]
   [1.0234479  0.7635077  0.00564644]
   [1.0228661  0.3304726  0.00500536]
   [0.8924433  0.9591879  0.02035429]
   [0.85795826 0.23249047 0.04497717]
   [0.8537795  0.750729   0.00219135]
   [0.77421063 0.4712658  0.00999798]]]]


SyntaxError: invalid syntax. Perhaps you forgot a comma? (3644951125.py, line 1)

In [48]:
c


NameError: name 'c' is not defined